### ISSUE TITLE
Default Image

### ISSUE THREAD

**Issue by blakemorgan** [byuweb/byu-news-component#3]
If story doesn't have a featured image, it needs a default image.

**Comment by blakemorgan** [comment]
We need to find out from the design group what the default image should be.

**Comment by Aleniras** [comment]
Yes. Can you send me a screen shot? We may even want to include @hadfieldjoe on this as he's probably better aware of great "default BYU" images.

**Comment by blakemorgan** [comment]
This is a picture of what we're working with (pardon the distorted images, we are working to fix that). The default image would go where the images are in this screenshot.

![news component](https://user-images.githubusercontent.com/9389424/29473154-e1e0a7ce-8413-11e7-86d9-e2057acd391e.PNG)

**Comment by Aleniras** [comment]
It's looking good! I think Joe is best for selecting the default "BYU" image. Let me know if he'd rather I do it though, and I can help.  Also, any chance we can put the date under the title of the event? Putting it at the bottom seems to confuse it with the event after it.

**Comment by hadfieldjoe** [comment]
On our news site, we don't have a default image because the expectation is that every story will have its own thumbnail.

**Comment by blakemorgan** [comment]
Closing because there will always be a picture.
